### ISSUE TITLE
Getting responses from UPI apps 

### ISSUE THREAD

**Issue by Bhavya2118** [sreegithck/AndroidWebView_FULL#3]
Greetings sir,
What I understand is this module is, it's an ' empty ' App in which I can in a way embed my website to give the end user a native app like experience. I wanted to ask if a deeplink is placed in this module, and clicked..it takes to the chosen UPI app with prefilled details, and after the payment, will the UPI app send a payment status (successful/submitted/failed) back to the website (placed in your app framework) ? Can't a website running from a browser do the same? Invoking UPI app from anywhere is possible, but can we receive the response back from it, to a website in your module and to a normal website/progressive web app?

**Comment by sreegithck** [comment]
Yes you will get the response from UPI app like success, cancelled, failed, the app not found etc. How you are going to handle it in your web app is depends. Since its a payment/money-related stuff it is not included over here. Refer NPCI  guide for the same

https://www.npci.org.in/sites/default/files/UPI%20Linking%20Specs_ver%201.6.pdf

You can get a response back to your APP from UPI APPS, Suggest you go through the above one and explore.

**Comment by Bhavya2118** [comment]
Okay so, can I get a response if I'm running my web app in a browser, and not using your module?

**Comment by sreegithck** [comment]
Yes you can get it. This module is just a web view capable to trigger the URI and other mentioned stuff.

**Comment by Bhavya2118** [comment]
I hope you got my last query clearly sir. I want to know can I receive a response if I open UPI deeeplink placed in my website , which is open in the chrome browser only? I mean without using your module at all. Is it generally possible I'm asking?

**Comment by sreegithck** [comment]
Yes it is possible, by catching the response back. As mentioned before please go through NPCI guide and learn more
